- src/main.rs
> Test CI thing

- api/lua/client.lua
- api/lua/example_config.lua
- api/lua/process.lua
- src/state.rs
Raises the fd limit to prevent a "Too many open files" crash.
> Raise fd limit, add minor docs

- Cargo.toml
- api/lua/example_config.lua
- api/lua/pinnacle.lua
- api/lua/process.lua
- src/state.rs
Didn't like that opening up something that used process output ate up 3 threads, so this fixes that
> Move from threads to async for process output

- src/backend/udev.rs
- src/state.rs
> Reschedule ConnectForAllOutputs callbacks until stream exists

- README.md
- src/backend/udev.rs
- src/input.rs
This is some disgusting, vile code I've just added, need to clean that up
> Add vt switching

- src/layout.rs
> Fix floating windows not reappearing

- src/backend/udev.rs
- src/backend/winit.rs
- src/focus.rs
- src/handlers.rs
- src/handlers/xdg_shell.rs
- src/input.rs
- src/layout.rs
- src/main.rs
- src/render.rs
- src/state.rs
- src/state/api_handlers.rs
- src/tag.rs
- src/window.rs
- src/window/window_state.rs
> Fix rendering

- Cargo.toml
- src/backend/udev.rs
- src/backend/winit.rs
- src/focus.rs
- src/handlers/xdg_shell.rs
- src/handlers/xwayland.rs
- src/input.rs
- src/layout.rs
- src/main.rs
- src/state/api_handlers.rs
- src/window.rs
- src/window/window_state.rs
Currently:
- Fixes #82 
- Closes #83
> Fix some stuff

- Cargo.toml
- README.md
- api/lua/metaconfig.toml
- api/lua/pinnacle.lua
- build.rs
- install_libs.sh
- src/backend/udev.rs
- src/config.rs
- src/config/api.rs
- src/input.rs
- src/state.rs
> Load default config when config crashes

- api/lua/output.lua
- src/backend/udev.rs
- src/config.rs
- src/config/api/msg.rs
- src/output.rs
- src/state/api_handlers.rs
- src/window/window_state.rs
> Save output state on disconnect, restore on reconnect

- src/backend.rs
- src/backend/udev.rs
- src/backend/udev/utils.rs
- src/backend/winit.rs
- src/input.rs
- src/state.rs
It's 1500 lines of stuff I copied from Anvil and there are some things that don't need to be there.
> Clean up udev file

- src/backend.rs
- src/backend/udev.rs
- src/input.rs
Fixes #51 
Edit: may or may not fix #99, so I'm gonna close it here unless it happens again
> Clear drm overlay planes on tty switch

- api/lua/example_config.lua
- api/lua/msg.lua
- api/lua/output.lua
- api/lua/pinnacle.lua
- api/lua/tag.lua
- api/lua/test_config.lua
- api/lua/window.lua
- api/lua/window_rules.lua
- src/input.rs
- src/output.rs
- src/state/api_handlers.rs
- src/tag.rs
- src/window/window_state.rs
Currently a bunch of API functions can return nil.
This PR will change that to have them return invalid objects that can still be used; the compositor will just ignore them. This should make the API a bit easier to use.
> Make Lua API more nil-safe

- .github/workflows/ldoc.yml
- .github/workflows/rust.yml
- .github/workflows/rustdoc.yml
- README.md
- api/rust/Cargo.toml
- api/rust/examples/example_config.rs
- api/rust/metaconfig.toml
- api/rust/src/input.rs
- api/rust/src/input/libinput.rs
- api/rust/src/lib.rs
- api/rust/src/msg.rs
- api/rust/src/output.rs
- api/rust/src/pinnacle.rs
- api/rust/src/process.rs
- api/rust/src/tag.rs
- api/rust/src/window.rs
- api/rust/src/window/rules.rs
I like me that type safety and also `panicked at 'already borrowed: BorrowMutError'` :grinning:
And I'm sure you do too, so here's the Rust API!
Pinnacle was architected at the start to use serialization over a Unix socket to enable configuration using multiple different programming languages. This was because while I wanted Lua to be the main config language from my use of Awesome, I also really like Rust and having to yell at the borrow checker.
It also makes configuration in basically every other language that can connect to a Unix socket and serialize stuff possible, but that would require I work out an API spec for those of you who actually want to spend time implementing that stuff.
> Add Rust API

- src/api/handlers.rs
- src/window/window_state.rs
> Schedule render on `SetLayout`

- src/api/handlers.rs
- src/backend/udev.rs
- src/focus.rs
- src/grab/move_grab.rs
- src/grab/resize_grab.rs
- src/handlers.rs
- src/input.rs
- src/layout.rs
- src/render.rs
- src/window.rs
- src/window/blocker.rs
- src/window/window_state.rs
> Fix output display on udev

- src/grab/resize_grab.rs
> Fix floating windows sometimes not storing geometry

- src/handlers.rs
- src/handlers/xdg_shell.rs
- src/layout.rs
- src/state.rs
- src/window/blocker.rs
> Impl wlr_data_control

- api/rust/src/input.rs
- api/rust/src/lib.rs
- api/rust/src/output.rs
- api/rust/src/pinnacle.rs
- api/rust/src/process.rs
- api/rust/src/tag.rs
- api/rust/src/window.rs
> Replace all `futures::executor::block_on` with tokio equivalent

- api/lua/examples/default/default_config.lua
- api/lua/pinnacle-api-dev-1.rockspec
- api/lua/pinnacle.lua
- api/lua/pinnacle/grpc/protobuf.lua
- api/lua/pinnacle/output.lua
- api/lua/pinnacle/render.lua
- api/protocol/pinnacle/output/v0alpha1/output.proto
- api/protocol/pinnacle/render/v0alpha1/render.proto
- api/rust/examples/default_config/main.rs
- api/rust/src/lib.rs
- api/rust/src/output.rs
- api/rust/src/render.rs
- pinnacle-api-defs/build.rs
- pinnacle-api-defs/src/lib.rs
- src/api.rs
- src/backend.rs
- src/backend/udev.rs
- src/backend/udev/drm_util.rs
- src/backend/winit.rs
- src/config.rs
- src/render.rs
TODO:
- So it turns out trying to render a window at a different scale than everything else will need some major refactoring/hacks to work, so that is being held off for a later date
> Add HiDPI support

- src/handlers.rs
- src/state.rs
- wlcs_pinnacle/src/lib.rs
I can run pinnacle with it and stuff still works, and the code looks reasonable, but not sure yet how to "properly" test it yet, as I don't yet know who uses this protocol or how I can verify it works as it should
And not a huge fan of the `is_client_restricted` being defined on `State`, but also haven't come up with a better place to put it either
> Add security-context-v1

- TODO.md
- src/api.rs
- src/backend.rs
- src/backend/dummy.rs
- src/backend/udev.rs
- src/backend/winit.rs
- src/cli.rs
- src/config.rs
- src/handlers.rs
- src/handlers/xwayland.rs
- src/input.rs
- src/main.rs
- src/state.rs
- tests/common/mod.rs
- wlcs_pinnacle/src/lib.rs
- wlcs_pinnacle/src/main_loop.rs
Ignore the fact that there's a 2000 line diff commit haha
TODO:
- ~Make tag and window id counters not static~ Saving that for another commit because I have a really bad habit of lopping a bunch of separate things in a single PR
> Uncouple stuff and do some cleanup

- Cargo.lock
- Cargo.toml
- src/backend.rs
- src/backend/udev.rs
- src/backend/winit.rs
- src/focus/keyboard.rs
- src/focus/pointer.rs
- src/handlers.rs
- src/handlers/session_lock.rs
- src/handlers/xwayland.rs
- src/input.rs
- src/output.rs
- src/render.rs
- src/state.rs
NOT blatantly plagiarized from Niri this time gj me
TODO:
> Implement session lock

- README.md
- api/lua/.luarc.json
- api/lua/examples/default/.luarc.json
- api/lua/examples/default/default_config.lua
- api/lua/examples/default_no_snowcap/.luarc.json
- api/lua/examples/default_no_snowcap/default_config.lua
- api/lua/examples/default_no_snowcap/metaconfig.toml
- api/lua/pinnacle-api-dev-1.rockspec
- api/lua/pinnacle.lua
- api/lua/pinnacle/input.lua
- api/lua/pinnacle/snowcap.lua
- api/rust/src/snowcap/integration.rs
- justfile
- src/main.rs
Ayo the Lua side is here
TODO:
- So it doesn't but I got the tests to work at least
> Preliminary Snowcap integration (Lua)

- src/api/window.rs
This fixes an issue when trying to move window to tag on another output. Currently, only the layout of the target output gets updated. This updates both the source and target layout.
> Fixes source output layout not being updated when moving window to tag on another output

- src/grab/move_grab.rs
- src/handlers/window.rs
When changing LayoutMode, if the window previously had a floating geometry (i.e. it has been floated or spilled before), the window restores it. This lead to some window jumping back to their previous output while being attached to the current output tag.
~~With this fix, we relocate the window on mode change if they do not intersect with current output.~~
~~The intersection check if to restore the previous location for case where the left side of a floating window would be inside another monitor. Without it, you could have 'weird' behavior where toggling fullscreen twice (without moving the window) would move the window.~~
~~This however means that a floating window can still be reattached to its previous output **if** it previously intersected with the one if was fullscreen-ed on.
I …
> window: Update position on LayoutMode changes

- snowcap/api/lua/snowcap/grpc/defs.lua
- snowcap/api/lua/snowcap/layer.lua
- snowcap/api/lua/snowcap/widget.lua
- snowcap/api/protobuf/snowcap/widget/v1/widget.proto
- snowcap/api/rust/src/layer.rs
- snowcap/api/rust/src/lib.rs
- snowcap/api/rust/src/widget.rs
- snowcap/api/rust/src/widget/button.rs
- snowcap/src/api/input/v0alpha1.rs
- snowcap/src/api/input/v1.rs
- snowcap/src/api/layer/v0alpha1.rs
- snowcap/src/api/layer/v1.rs
- snowcap/src/api/widget.rs
- snowcap/src/api/widget/v1.rs
- snowcap/src/handlers.rs
- snowcap/src/layer.rs
- snowcap/src/server.rs
- snowcap/src/state.rs
- snowcap/src/widget.rs
This PR adds buttons to Snowcap.
Todos:
- Beyond this PR: figure out how to mutate widgets from a button callback
> snowcap: Add button widget
