README.md, src/backend/winit.rs, src/handlers.rs, src/handlers/xdg_shell.rs, src/handlers/xwayland.rs, src/layout.rs, src/state.rs, src/window/window_state.rs
This PR fixes #29 and other flickering by pausing rendering until all windows have committed pending changes. This *will* introduce some latency when windows resize, but the fix to flickering should more than makeup for that.
=> Fix flickering

Cargo.toml, src/backend/udev.rs, src/backend/winit.rs, src/grab/move_grab.rs, src/handlers.rs, src/handlers/xdg_shell.rs, src/render.rs
Alrighty I thought that I would need to change the rendering on udev but apparently the problem I've been seeing (jittery scrolling) doesn't happen in release mode, which tells me that I might be doing something that takes too long, because Anvil doesn't have this issue.
But hey there  are some flickering mitigations like cropping all windows to the expected size. <sup>not gonna lie it's kinda feeling like i'm slapping bandages on top of other bandages, maybe i'll get around to working in a system for atomic updates across all windows</sup>
=> Flickering mitigations

.github/workflows/ldoc.yml, api/lua/example_config.lua, src/backend.rs, src/backend/udev.rs, src/backend/winit.rs, src/handlers/xdg_shell.rs, src/layout.rs, src/window.rs, src/window/blocker.rs
If you open a new window that is tiled, it will take a bit for it to show up on screen, but all other tiled windows will have already resized by then. This manifests itself as slight flickering.
Currently the compositor just doesn't render new frames when this happens. While this *works*, it's pretty hacky. Additionally it causes the cursor to freeze up when new frames aren't being rendered.
The solution to this is to attach a [`Blocker`](https://smithay.github.io/smithay/smithay/wayland/compositor/trait.Blocker.html) to tiled windows to prevent them from displaying updates while the newly opened window takes time to present itself.
There is currently still an ever so slight flicker that is hopefully easily remediable, but luckily it's not too jarring.
TODO: this only works when opening a …
=> Use a `Blocker` implementation instead of halting rendering

Cargo.lock, Cargo.toml, api/lua/example_config.lua, api/lua/msg.lua, api/lua/process.lua, api/rust/src/msg.rs, api/rust/src/process.rs, src/api.rs, src/api/handlers.rs, src/api/msg.rs, src/config.rs, src/main.rs, src/state.rs
=> Move spawn_once logic into compositor

Cargo.lock, Cargo.toml, api/lua/pinnacle-api-dev-1.rockspec, api/lua/pinnacle/grpc/client.lua, api/lua/pinnacle/grpc/protobuf.lua, api/lua/pinnacle/output.lua, api/lua/pinnacle/signal.lua, api/lua/pinnacle/tag.lua, api/lua/pinnacle/tag/layout.lua, api/lua/pinnacle/window.lua, api/protocol/pinnacle/output/v0alpha1/output.proto, api/protocol/pinnacle/signal/v0alpha1/signal.proto, api/rust/Cargo.toml, api/rust/examples/default_config/main.rs, api/rust/src/input.rs, api/rust/src/lib.rs, api/rust/src/output.rs, api/rust/src/process.rs, api/rust/src/signal.rs, api/rust/src/tag.rs, api/rust/src/window.rs, pinnacle-api-defs/build.rs, pinnacle-api-defs/src/lib.rs, src/api.rs, src/api/signal.rs, src/backend/udev.rs, src/config.rs, src/state.rs, src/window.rs, src/window/window_state.rs
This is a successor to #158, which is way too large in scope; I definitely bit off more than I could chew.
Compared to that PR, this one only adds 4 signals:
- Output connect
- Layout
- Window pointer enter
- Window pointer leave
These signals won't have much use until I add stuff to make them useful.
Additionally, this PR implements application-level flow control for signals. In #158, I ran into problems where the compositor sent signals too fast and the client couldn't keep up. This PR should fix that by having the APIs signal readiness to receive more signals.
=> Scaffold a signal system

api/lua/examples/default/default_config.lua, api/lua/pinnacle/grpc/protobuf.lua, api/lua/pinnacle/tag.lua, api/lua/pinnacle/util.lua, api/lua/pinnacle/window.lua, api/protocol/pinnacle/tag/v0alpha1/tag.proto, api/protocol/pinnacle/v0alpha1/pinnacle.proto, api/protocol/pinnacle/window/v0alpha1/window.proto, api/rust/examples/default_config/main.rs, api/rust/src/tag.rs, api/rust/src/window.rs, src/api.rs, src/backend/udev.rs, src/backend/winit.rs, src/focus.rs, src/handlers.rs, src/handlers/xdg_shell.rs, src/handlers/xwayland.rs, src/input.rs, src/layout.rs, src/output.rs, src/state.rs
This PR reworks focus to be per output and not global. It also decouples windows' z-index from the keyboard focus stack.
Additionally, `Window.set_focused` has been added, meaning this PR also enables sloppy focus.
=> Rework focus and add `Window.set_focused`

.github/workflows/ci.pinnacle.yml, Cargo.toml, README.md, api/protocol/pinnacle/v0alpha1/pinnacle.proto, api/rust/src/layout.rs, api/rust/src/lib.rs, api/rust/src/pinnacle.rs, api/rust/src/signal.rs, build.rs, src/api.rs, src/api/layout.rs, src/config.rs, src/input.rs, src/state.rs
This PR embeds the default Rust config into the binary, meaning that Pinnacle no longer needs to run a separate process for the default config. It removes the hard dependency on Luarocks. This is halfway to resolving #214 and unblocking #215; the other half is to create a Makefile or some other external runner to copy over protobuf definitions and default configs for `pinnacle config gen`, but that's for another PR/commit.
This *does* mean that users who want to use the Lua API will need to manually `cd` into [`api/lua`](https://github.com/pinnacle-comp/pinnacle/tree/main/api/lua) and run `luarocks make [--local]`. Edit: Or stick that in the Makefile maybe idk my brain's fried rn
Also build times went up by like 9% :P. I considered locking the embedding behind a feature flag to mitigate …
=> Embed default rust config in binary

src/api.rs, src/api/window.rs, src/handlers.rs, src/protocol.rs, src/protocol/foreign_toplevel.rs, src/state.rs, src/window.rs, src/window/window_state.rs
As always, blatantly plagiarized from Niri.
TODO:
- ~*Maybe* work on tracking the parent?~
- Too lazy rn
- Will switch to the window's first tag if the window is not on an active tag
=> Implement wlr-foreign-toplevel-management

.github/workflows/ci.pinnacle.yml, Cargo.lock, Cargo.toml, README.md, api/lua/pinnacle/grpc/defs.lua, api/lua/pinnacle/output.lua, api/lua/pinnacle/util.lua, api/protocol/pinnacle/output/v0alpha1/output.proto, api/rust/src/output.rs, src/api.rs, src/backend.rs, src/backend/dummy.rs, src/backend/udev.rs, src/backend/udev/drm/util.rs, src/backend/winit.rs, src/config.rs, src/handlers.rs, src/layout.rs, src/output.rs, src/protocol.rs, src/protocol/gamma_control.rs, src/protocol/output_management.rs, src/protocol/output_power_management.rs, src/state.rs, src/tag.rs, src/window.rs
TODO:
- ~~Move to libdisplay-info for EDID parsing~~
- Splitting off of this PR
=> Better output management

.github/workflows/ci.pinnacle.yml, .github/workflows/ldoc.yml, .github/workflows/rustdoc.yml, .gitmodules, Cargo.lock, Cargo.toml, README.md, TODO.md, api/lua/examples/default/default_config.lua, api/lua/pinnacle/grpc/defs.lua, api/lua/pinnacle/input.lua, api/protocol/pinnacle/input/v0alpha1/input.proto, api/rust/Cargo.toml, api/rust/examples/default_config/for_copying/Cargo.toml, api/rust/examples/default_config/main.rs, api/rust/examples/default_config_no_snowcap/main.rs, api/rust/examples/default_config_no_snowcap/metaconfig.toml, api/rust/src/input.rs, api/rust/src/lib.rs, api/rust/src/signal.rs, api/rust/src/snowcap.rs, api/rust/src/snowcap/integration.rs, flake.nix, src/api.rs, src/handlers.rs, src/input.rs, src/main.rs, src/state.rs, wlcs_pinnacle/Cargo.toml
This PR adds preliminary integration for [Snowcap](https://github.com/pinnacle-comp/snowcap), the very, *very* WIP widget system for Pinnacle. Snowcap integration is gated by the `snowcap` feature, enabled by default.
Snowcap is currently, for the most part, a thin API wrapper around [Iced](https://iced.rs/). As such, the current Rust API closely mirrors their widget API.
The only currently implemented widgets are row, column, scrollable, container, and text. Using those, a goal for this PR is to implement an exit prompt and a keybind list a la Awesome.
The Lua side has not been implemented yet and will be the target of a future PR.
TODO:
- ~~Don't really like this tbh~~ found a decent way to do it yay
=> Preliminary snowcap integration (Rust)

api/lua/pinnacle/grpc/defs.lua, api/lua/pinnacle/window.lua, api/protocol/pinnacle/window/v0alpha1/window.proto, api/rust/src/window.rs, api/rust/src/window/rules.rs, src/api/window.rs, src/grab/move_grab.rs, src/grab/resize_grab.rs, src/handlers.rs, src/handlers/foreign_toplevel.rs, src/handlers/window.rs, src/handlers/xdg_shell.rs, src/handlers/xwayland.rs, src/input.rs, src/layout.rs, src/output.rs, src/render.rs, src/render/util/snapshot.rs, src/window.rs, src/window/rules.rs, src/window/window_state.rs, wlcs_pinnacle/src/main_loop.rs
This PR comes with improvements to window state handling (floating, fullscreen, maximized).
Improvements include:
- Pinnacle will now *finally* attempt to open Wayland windows as floating when necessary, like the save prompt in Firefox. This closes #85 which was opened a whopping 9 months ago haha
- Fixed the bit where you could drag fullscreen and maximized windows when the window was previously floating
- Fixed xterm taking like 5 seconds to open
- In classic xwayland fashion, this introduces a regression where you now need to run Intellij Idea with `_JAVA_AWT_WM_NONREPARENTING=1` to get it to appear correctly
Things that need doing and thinking about:
- Unified `floating_or_tiled` with the `fullscreen_or_maximized` state, which now feeds into `Pinnacle::update_window_state`.
=> Improve window state handling

Cargo.lock, Cargo.toml, src/api.rs, src/backend.rs, src/backend/udev.rs, src/backend/udev/drm/util.rs, src/backend/udev/frame.rs, src/backend/winit.rs, src/cursor.rs, src/focus.rs, src/handlers.rs, src/layout/transaction.rs, src/output.rs, src/render.rs, src/render/util/snapshot.rs, src/state.rs, src/window/window_state.rs
This PR brings Pinnacle's rendering loop more in line with niri and cosmic-comp. Specifically, it:
- Properly throttles rendering such that frame submissions with no damage wait for a frame before allowing another render
- Prevents clients from busy-looping commits by only allowing sending frame callbacks once per vblank
As a result, rendering performance has improved by quite a bit. A YouTube video used to take around 6-7% of my CPU; now it takes around 1%.
TODO:
Should fix #266
=> Rendering improvements

src/focus/pointer.rs, src/handlers/session_lock.rs, src/input.rs, src/input/bind.rs
Allows a pointer click to change lock surface focus, and only auto-focuses on the first lock surface to remove the need for the user to click on the first lock surface to get keyboard focus for gtklock.
Fixes #287
=> Fix lock surface focus

api/lua/pinnacle.lua
The custom searcher in pinnacle.lua expect the path_searcher to exist with index 2, which is not guaranteed.
As an example if the config uses luarocks.loader instead of editing the environment, the loader will prepend itself to the searcher list, which offset everything, so the custom searcher will now call preload_searcher instead.
This PR fixes that issue by iterating over all existing loaders.
The second commit additionally requires `luarocks.loader`, but in a pcall to prevent a crash if luarocks.loader does not exists. 
Currently, it's called after the loader setup, which might not be the best place.
@Ottatop this means that `snowcap` might be searched first in `luarocks.loader` (in case it wasn't added to the default config), which will fail as long as `snowcap` doesn't exist as a …
=> luaapi: improve custom searcher logic

justfile, snowcap/justfile
This PR fixes various issue I encountered while building from main.
- `just` invocation failed if started without `LUA_CPATH` in the environment
- `just install` failed due some dependencies failing to build
- `just clean` complains about trying to remove `lua-grpc-client` even though the rock no longer exists
> `just install` failed due some dependencies failing to build
This is outside of pinnacle control. `luaossl`, a dependency of `http`, fails to build on recent compilers due to some breaking changes in recent C syntax.
However, the way luarocks is invoked did not allow to search for dependencies in the system wide tree, so I changed the behavior.
The last commit of the series could be removed. I uses luarocks to retrieve the paths when available, instead of depending on a hardcoded …
=> justfile: Fix various error when building from source

src/layout.rs
The window have two 'properties' when it come to their location. One is the surface location (i.e. where the surface is mapped in global space), the other is the floating location (used to restore the surface when switching to a floating mode).
Only the surface location was updated on a resize previously.
fixes: #332
=> layout: Update window floating loc on resize

src/api/window.rs
Previous behavior was checking in which quadrant the pointer was when starting the resize, which
only allowed corner resizing.
~~This patch compute the distance between the cursor location and a fixed set of point.~~
~~The second commit fixes a minor glitch where clicking just outside the main surface would use the shadow as the window location. This had a weird behavior where top and left edges worked as expected, but bottom and right edge had the behavior from the opposing edge.~~
The new behavior is to split the area into a 3x3 grid, and find in which cell the pointer falls into.
The center cell cannot really use that behavior. Instead we use some vector math to determine which the edge to use.
fixes #162
=> Make compositor-initiated window resizing also use single edges

api/lua/pinnacle/snowcap.lua, api/rust/src/snowcap.rs, snowcap/api/lua/snowcap/grpc/defs.lua, snowcap/api/lua/snowcap/layer.lua, snowcap/api/protobuf/snowcap/layer/v1/layer.proto, snowcap/api/rust/src/layer.rs, snowcap/src/api/layer/v0alpha1.rs, snowcap/src/api/layer/v1.rs, snowcap/src/handlers.rs, snowcap/src/layer.rs, snowcap/src/lib.rs, snowcap/src/state.rs, snowcap/src/wgpu.rs, snowcap/src/widget.rs
This PR changes the way Snowcap layer surfaces are sized. Previously, they had a fixed size set at the time of creation. Now, layers will size based on the widget they hold. That is, a widget with `Length::Fill` will fill the whole output, and one with `Length::Shrink` will shrink as much as possible. For the previous fixed behavior, the root widget should be `Length::Fixed(size)`.
Additionally, if the output scale increases enough to make the layer too big, it will now resize downwards to fit.
Todos:
- The size of a widget is bound by the logical size of the output it's on. Right now, with integer scale, this means that a widget on an output with a scale of 1.5 thinks it's on a smaller output than it actually is. We need fractional scale to fix this.
=> snowcap: Size layers based on the widget

api/lua/pinnacle/output.lua, api/rust/src/output.rs, tests/integration/api/output.rs
This PR adds part of #324 to the API, namely the OutputHandle::active_tags method.
Since protobuf allows to add new field in a backward compatible way, I've just added a filter argument.
The filter argument is setup to fallback on the 'All' filter, so client/config built for the previous API will still behave as expected.
The client/config facing api gets an additional `active_tag` method, and I've added an inactive method as well.
=> api: add [in]active tags filtering to OutputHandle

api/lua/pinnacle/grpc/defs.lua, api/protobuf/pinnacle/window/v1/window.proto, src/api/window/v1.rs
As mentioned in #340, this adds a typed response to window::MoveToOutput RPC
=> api/window: add response to WindowHandle::MoveToOutput RPC

api/lua/pinnacle/grpc/defs.lua, api/lua/pinnacle/window.lua, api/protobuf/pinnacle/window/v1/window.proto, api/rust/src/window.rs, src/api/window.rs, src/api/window/v1.rs, src/focus.rs, tests/integration/api/window.rs
This PR adds a RPC to lower a window to the back.
I mentioned it in #324, when the main means of interacting with the compositor is through keyboard inputs, it's a bit tedious to switch to a lower window, since you have to basically guess where the window is. This gives tools to lower the currently focused window to the back of the Z-Buffer.
One thing I'm unsure of is whether lowering a fullscreen/maximized window make sense.
I've allowed it because in my opinion, RPCs is in the API should gives building block for configuration, not restrict whats possible as long as it does not leave the compositor in a bad state.
=> Add WindowHandle::lower

src/window.rs, tests/integration/common/client.rs, tests/integration/common/fixture.rs, tests/integration/main.rs, tests/integration/protocol.rs, tests/integration/protocol/xdg_shell.rs
This started as part of #348, because I noticed `set_maximize` might not be up to spec because of `update_window_layout_and_layout`.
Specifically: 
> If the surface was already maximized, the compositor will still emit a configure event with the "maximized" state.
and
>If the surface is in a fullscreen state, this request has no direct effect. It may alter the state the surface is returned to when unmaximized unless overridden by the compositor.
are not implemented.
I'm making it a standalone PR because I want to cover ~~the whole protocol~~ toplevel related functions, and it's possible this one will be ready before #348 (another possibility is that I split out refactoring `update_window_layout_and_layout` from #348 since that PR primary goal is already implemented).
=> XDG Shell protocol: Add tests to ensure protocol correctness 

src/backend/udev.rs, src/config.rs, src/output.rs
This PR introduces the powered field to `ConnectorSavedState` to correctly handle monitors that automatically try to reconnect after being powered off.
When an output is deactivated, its last known powered state is now saved. Upon reconnection, this saved state is reapplied, ensuring that an output intended to be off remains off. This resolves power-looping issues as discussed in [#362](https://github.com/pinnacle-comp/pinnacle/pull/362).
~Additionally, this change removes the creation of `ConnectorSavedState` from the `set_loc` API call. As far as I can tell there is no situation where that would be used, as it would always be overwritten by either `set_enable` or `remove_output`.~
=> Add powered to ConnectorSavedState

.gitignore, src/handlers.rs, src/handlers/ext_workspace.rs, src/protocol.rs, src/protocol/ext_workspace.rs, src/state.rs, src/tag.rs
I've followed the niri approach - predominantly - here, while also using the cosmic implementation as a reference. this PR has been tested with waybar as the ext-workspace-v1 client.
important notes:
1. in order to preserve tag behavior, we don't automatically deactivate active tags when receiving an activate request on a new tag. most compositors treat workspace activation like our `api::tag::switch_to`. in order to treat tags like workspaces, waybar and other clients will need a config option to issue those deactivate on active tags, in concert with the activation request. we can maybe update our own config option as part of the API that changes the behavior of activate to use `api::tag::switch_to` instead of `api::tag::set_active`.
2. I manually set up a test client to check workspace …
=> feat: implement ext-workspace-v1

nix/modules/home-manager/default.nix
home-manager supports setting up nixGL so make use of that in the
home-manager module to enable correctly launching pinnacle wrapped with
the nixGL nixVulkan* wrappers. home-manager also provides the ability to
set up xdg desktop portals, similar to the nixos options, so expose
those options as well for non-NixOS.
=> feat(nix): add nixGL support for non-NixOS
